changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking changes
      labels:
        - breaking changes
    - title: Home Assistant and MQTT
      labels:
        - home-assistant
        - mqtt
    - title: Docker and registry handling
      labels:
        - docker
        - registry
    - title: Features
      labels:
        - enhancement
        - feature
      exclude:
        labels:
          - dependencies
          - fix
          - chore
          - docs
          - test
          - performance
          - security
          - refactoring
          - breaking changes
    - title: Fixes
      labels:
        - fix
        - bug
    - title: Dependencies
      labels:
        - dependencies
    - title: Tests
      labels:
        - test
    - title: Documentation
      labels:
        - docs
    - title: Maintenance
      labels:
        - chore
        - refactoring
        - performance
        - security
